// Cloudflare Worker entry that wraps the OpenNext-generated worker so we can
// attach a `scheduled` handler for Cron Triggers. The OpenNext build produces
// `.open-next/worker.js` (only `fetch` + DO exports); we re-export the durable
// objects unchanged and layer on our cron handler.
//
// Cloudflare global types (`ExecutionContext`, `ScheduledController`, etc.)
// are not installed as a typings package in this project. We type the surface
// locally with the minimum shape needed instead of pulling in
// `@cloudflare/workers-types`.

// @ts-ignore .open-next/worker.js is generated by `opennextjs-cloudflare build`
import openNextWorker from "./.open-next/worker.js"
// @ts-ignore same as above; re-export DOs unchanged so Cloudflare can bind them
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js"

import { promoteBacklog } from "./src/lib/backlog-promotion"

type WaitUntilCtx = { waitUntil: (p: Promise<unknown>) => void }
type FetchFn = (req: Request, env: unknown, ctx: WaitUntilCtx) => Promise<Response>

export default {
  fetch: (openNextWorker as { fetch: FetchFn }).fetch,
  async scheduled(_event: unknown, _env: unknown, ctx: WaitUntilCtx) {
    ctx.waitUntil(
      promoteBacklog()
        .then((r) =>
          console.log(`[cron promote-backlog] promoted=${r.promoted} failed=${r.failed}`),
        )
        .catch((e) => console.error("[cron promote-backlog] error:", e)),
    )
  },
}
