export const NOTION_PROPS = {
  TITLE:      "タイトル",
  STATUS:     "Status",
  PRIORITY:   "Priority",
  DUE:        "Due",
  TAG:        "Tag",
  ASSIGNEE:   "Assignee",
  SOURCE:     "Source",
  SOURCE_URL: "SourceURL",
  PARENT:     "親タスク",
  CHILD:      "子タスク",
  PREV:       "前タスク",
  NEXT:       "次タスク",
  FILES:      "添付ファイル",
  LOCATION:   "Location",
} as const
